export const SET_EXPENSES = 'SET_EXPENSES'
export const ADD_EXPENSE = 'ADD_EXPENSE'
export const EDIT_EXPENSE = 'EDIT_EXPENSE'
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE'
export const LOADING_EXPENSE_START = 'LOADING_EXPENSE_START'
export const CLEAR_EXPENSES = 'CLEAR_EXPENSES'

export const LOADING_USER_START = 'LOADING_USER_START'
export const SET_USER_DATA = 'SET_USER_DATA'
export const CLEAR_USER = 'CLEAR_USER'
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'
export const CHANGE_CATEGORIES = 'CHANGE_CATEGORIES'

export const API_CALL_START = 'API_CALL_START'
export const API_CALL_FINISH_SUCCESS = 'API_CALL_FINISH_SUCCESS'
export const API_CALL_FINISH_FAIL = 'API_CALL_FINISH_FAIL'
export const UPDATE_FILTER = 'UPDATE_FILTER'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

export enum EActionTypes {
  SET_EXPENSES = 'SET_EXPENSES',
  ADD_EXPENSE = 'ADD_EXPENSE',
  EDIT_EXPENSE = 'EDIT_EXPENSE',
  REMOVE_EXPENSE = 'REMOVE_EXPENSE',
  LOADING_EXPENSE_START = 'LOADING_EXPENSE_START',
  CLEAR_EXPENSES = 'CLEAR_EXPENSES',

  LOADING_USER_START = 'LOADING_USER_START',
  SET_USER_DATA = 'SET_USER_DATA',
  CLEAR_USER = 'CLEAR_USER',
  CHANGE_CURRENCY = 'CHANGE_CURRENCY',
  CHANGE_CATEGORIES = 'CHANGE_CATEGORIES',

  API_CALL_START = 'API_CALL_START',
  API_CALL_FINISH_SUCCESS = 'API_CALL_FINISH_SUCCESS',
  API_CALL_FINISH_FAIL = 'API_CALL_FINISH_FAIL',
  CLEAR_API_CALL = 'CLEAR_API_CALL',
  UPDATE_FILTER = 'UPDATE_FILTER',
  ADD_NOTIFICATION = 'ADD_NOTIFICATION',
  REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION',
}